"""Added models for Contact, RecipeShare and Notification, modified slightly Recipe and User

Revision ID: 85c6979e047e
Revises: b1166c4d2983
Create Date: 2025-11-18 22:25:54.414803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c6979e047e'
down_revision = 'b1166c4d2983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_contacts_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('is_contacts_only')

    # ### end Alembic commands ###
